{% set name = "pylablib" %}
{% set version = "1.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pylablib-{{ version }}.tar.gz
  sha256: 146cc50948dc734a4b2d0521dd39120ecbd1457c7be3b0e1c55c876e76694ef6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numba
    - numpy
    - pandas
    - pyqt >=5.9
    - pyqtgraph
    - pyserial
    - python >=3.6
    - pyusb
    - pyvisa >=1.6
    - rpyc
    - scipy

test:
  imports:
    - pylablib
    - pylablib.core
  requires:
    - pip

about:
  home: https://github.com/AlexShkarin/pyLabLib
  summary: 'Code for use in lab environment: experiment automation, data acquisition, device communication'
  doc_url: https://pylablib.readthedocs.io/
  dev_url: https://github.com/AlexShkarin/pyLabLib/
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AlexShkarin
